# MySQL 접속 주소
spring.datasource.url=jdbc:mysql://localhost:3306/game

# MySQL JDBC 드라이버
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MySQL 사용자 계정
spring.datasource.username=root

# Docker 실행 시 설정한 root 비밀번호
spring.datasource.password=1234

# 기존 데이터는 유지하면서 Entity 변경사항을 DB 테이블에 반영
spring.jpa.hibernate.ddl-auto=update